version: "3.8"

services:
  mysql-db:
    image: mysql/mysql-server:5.7
    container_name: mysql_DB_container
    restart: unless-stopped
    ports:
      - 3306:3306
    expose:
      - "3306"
    networks:
      - boilerplate
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpwd
      MYSQL_DATABASE: database_development
  server:
    build: ./server
    container_name: server_container
    depends_on: 
      - mysql-db
    ports:
      - 8000:8000
    expose:
      - "8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - mysql-db
    networks:
      - boilerplate
  client:
    build: ./client
    container_name: client_container
    environment:
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    links:
      - server
    
volumes:
  db_data:

networks:
  boilerplate:
    driver: bridge
